/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: Mohamed Osama
 *
 * Created on September 13, 2023, 2:33 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

/* Section : Includes */


/* Section : Macros Declaration */
#define INTERRUPT_FEATURE_ENABLE  0 
#define INTERRUPT_FEATURE_DISABLE  1 

#define INTERRUPT_PRIORITY_LEVELS_ENABLE  INTERRUPT_FEATURE_ENABLE 

#define EXTERNAL_INTERRUPT_INTx_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE 

#define EXTERNAL_INTERRUPT_OnCHANGE_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE 

#define ADC_INTERRUPT_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE

#define TIMER0_INTERRUPT_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE

#define TIMER1_INTERRUPT_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE

#define TIMER2_INTERRUPT_FEATURE_ENABLE INTERRUPT_FEATURE_DISABLE

#define TIMER3_INTERRUPT_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE

#define CCP1_INTERRUPT_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE
#define CCP2_INTERRUPT_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE

#define EUSART_TX_INTERRUPT_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE
#define EUSART_RX_INTERRUPT_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE

#define MSSP_INTERRUPT_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE

/* Section : Macro Functions Declaration */


/* Section : Data Types Declaration */


/* Section : Functions Declaration */

#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

